
name: Test - pa11y [STAGING]

on:
  push:
    branches:
      - master
  workflow_dispatch:


jobs:

  #  ┌───────────────────────────────────────────┐ 
  #  │                                           │░
  #  │                JOB: PA11Y                 │░
  #  │                                           │░
  #  └───────────────────────────────────────────┘░
  #   ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░


  linkcheck:


    runs-on: ubuntu-latest
    name: pa11y tests
    # RUN IF -pa11y or -test in commit message
    if: "contains(github.event.head_commit.message, ' -pa11y ') || contains(github.event.head_commit.message, ' -test ')"

    steps:

      - name: download pa11y-ci
        run: |
          sudo npm install -g npm@latest
          sudo npm install -g pa11y-ci


      - name: run pa11y
        run: |
          set -x
          echo '{ "defaults": { "ignore": [ "WCAG2AA.Principle1.Guideline1_4.1_4_3.G145.Fail", "WCAG2AA.Principle1.Guideline1_4.1_4_3.G18.Fail" ] } }' > pa11y_config.json
          ( pa11y-ci --json --config pa11y_config.json --sitemap https://staging.londonparkour.com/sitemap_index.xml &>> /tmp/pa11y-results.json) || true

      # # DEBUG with NGROK.
      # - name: Start SSH session
      #   uses: luchihoratiu/debug-via-ssh@main
      #   with:
      #     NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
      #     SSH_PASS: ${{ secrets.NGROK_SSH_PASS }}
      #     NGROK_REGION: eu

      - name: BLC Results
        uses: actions/upload-artifact@v2
        with:
          name: Results File  
          path: /tmp/pa11y-results.json


